### ISSUE TITLE
gem/bundler error when I run the 'console' workflow in the README

### ISSUE THREAD

**Issue by frewsxcv** [tildeio/helix#74] opened 2017-04-27 03:02 UTC
Really looking forward to incorporating Rust into my Ruby codebase :)

I took a look at this section: https://github.com/tildeio/helix#getting-started-with-helix-examples

I followed the instructions using Ruby 2.4.0 and here's how far I got:

```
> bundle exec rake build


Building helix runtime

bundle exec rake compile:native
Could not find gem 'rake-compiler (~> 0.9.7)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
rake aborted!
Command failed with status (7): [bundle exec rake compile:native...]
/private/tmp/helix/examples/console/Rakefile:15:in `block (4 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:286:in `block in with_clean_env'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:521:in `with_env'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:286:in `with_clean_env'
/private/tmp/helix/examples/console/Rakefile:14:in `block (3 levels) in <top (required)>'
/private/tmp/helix/examples/console/Rakefile:12:in `chdir'
/private/tmp/helix/examples/console/Rakefile:12:in `block (2 levels) in <top (required)>'
/private/tmp/helix/ruby/lib/helix_runtime/build_task.rb:39:in `block in define'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => build => helix:pre_build
(See full trace by running task with --trace)
```

**Comment by wagenet** [comment] 2017-04-27 05:10
@frewsxcv can you explain example what steps you're following? I don't see any reference to calling `bundle exec rake build` in the Getting Started section of the README.

**Comment by frewsxcv** [comment] 2017-04-27 12:51
The [previous section mentions `rake build`](https://github.com/tildeio/helix#helix). I tried doing the  [README tutorial](https://github.com/tildeio/helix#getting-started-with-helix-examples) again and am now getting a different error. Here's the full output:

```
corey@mac /p/t/tmp> git clone git@github.com:tildeio/helix.git
Cloning into 'helix'...
remote: Counting objects: 2459, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 2459 (delta 12), reused 0 (delta 0), pack-reused 2437
Receiving objects: 100% (2459/2459), 1.16 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1308/1308), done.

corey@mac /p/t/tmp> cd helix

corey@mac /p/t/t/helix (master)> cd examples/console

corey@mac /p/t/t/h/e/console (master)> rbenv local 2.4.0

corey@mac /p/t/t/h/e/console (master)> bundle install
Using rake 10.5.0
Using colorize 0.8.1
Using diff-lcs 1.3
Using thor 0.19.4
Using rspec-support 3.5.0
Using bundler 1.14.6
Using helix_runtime 0.5.0 from source at `../../ruby`
Using rspec-core 3.5.4
Using rspec-expectations 3.5.0
Using rspec-mocks 3.5.0
Using rspec 3.5.0
Bundle complete! 4 Gemfile dependencies, 11 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

corey@mac /p/t/t/h/e/console (master)> bundle exec rake irb
rake aborted!
LoadError: cannot load such file -- helix_runtime/native
/private/tmp/tmp/helix/ruby/lib/helix_runtime.rb:2:in `require'
/private/tmp/tmp/helix/ruby/lib/helix_runtime.rb:2:in `<top (required)>'
/private/tmp/tmp/helix/ruby/lib/helix_runtime/build_task.rb:2:in `require'
/private/tmp/tmp/helix/ruby/lib/helix_runtime/build_task.rb:2:in `<top (required)>'
/private/tmp/tmp/helix/examples/console/Rakefile:2:in `require'
/private/tmp/tmp/helix/examples/console/Rakefile:2:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)

corey@mac /p/t/t/h/e/console (master) [1]> bundle exec rake build
rake aborted!
LoadError: cannot load such file -- helix_runtime/native
/private/tmp/tmp/helix/ruby/lib/helix_runtime.rb:2:in `require'
/private/tmp/tmp/helix/ruby/lib/helix_runtime.rb:2:in `<top (required)>'
/private/tmp/tmp/helix/ruby/lib/helix_runtime/build_task.rb:2:in `require'
/private/tmp/tmp/helix/ruby/lib/helix_runtime/build_task.rb:2:in `<top (required)>'
/private/tmp/tmp/helix/examples/console/Rakefile:2:in `require'
/private/tmp/tmp/helix/examples/console/Rakefile:2:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)
```

**Comment by wagenet** [comment] 2017-04-27 14:36
Sorry about that! Should be fixed by c5589e3933788979897c60a4baaedc5f2aa54f27.

**Comment by frewsxcv** [comment] 2017-04-27 14:40
`rake compile` is not a task for me

```
corey@mac /p/t/h/e/console (cleanup)> bundle install
Using rake 10.5.0
Using colorize 0.8.1
Using diff-lcs 1.3
Using thor 0.19.4
Using rspec-support 3.5.0
Using bundler 1.14.6
Using helix_runtime 0.5.0 from source at `../../ruby`
Using rspec-core 3.5.4
Using rspec-expectations 3.5.0
Using rspec-mocks 3.5.0
Using rspec 3.5.0
Bundle complete! 4 Gemfile dependencies, 11 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
corey@mac /p/t/h/e/console (cleanup)> bundle exec rake --tasks
rake build    # Build console
rake clobber  # Remove build artifacts
rake irb      # Launch an IRB console for console
rake spec     # Run RSpec code examples
corey@mac /p/t/h/e/console (cleanup)> bundle exec rake compile
rake aborted!
Don't know how to build task 'compile' (see --tasks)
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)
```

**Comment by wagenet** [comment] 2017-04-27 14:42
@frewsxcv you shouldn't have to run it directly. The example Rakefiles will do it for you. If you do see the warning, it will be accompanied with a directory path in which you have to run it, which will point to the `ruby` directory in the project. Have you tried pulling the repo and then just running `bundle exec rake irb` in the `examples/console` directory?

**Comment by frewsxcv** [comment] 2017-04-27 14:46
> Have you tried pulling the repo and then just running bundle exec rake irb in the examples/console directory?

Yes. Here's the output:

```
corey@mac /p/t/h/e/console (master) [1]> git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

corey@mac /p/t/h/e/console (master)> git log | head -1
commit 894150d04ef3bb2ca6c57d413dfb03600c108681

corey@mac /p/t/h/e/console (master)> bundle exec rake irb
Unable to load helix_runtime/native. Please run `rake compile` in /private/tmp/helix/ruby.


Building helix runtime

bundle exec rake compile:native
Could not find gem 'rake-compiler (~> 0.9.7)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
rake aborted!
Command failed with status (7): [bundle exec rake compile:native...]
/private/tmp/helix/examples/console/Rakefile:15:in `block (4 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:286:in `block in with_clean_env'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:521:in `with_env'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:286:in `with_clean_env'
/private/tmp/helix/examples/console/Rakefile:14:in `block (3 levels) in <top (required)>'
/private/tmp/helix/examples/console/Rakefile:12:in `chdir'
/private/tmp/helix/examples/console/Rakefile:12:in `block (2 levels) in <top (required)>'
/private/tmp/helix/ruby/lib/helix_runtime/build_task.rb:39:in `block in define'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => irb => build => helix:pre_build
(See full trace by running task with --trace)
```

**Comment by wagenet** [comment] 2017-04-27 15:27
Looks like it wants you to run `bundle install` in the `ruby` directory of the project first. This is strange, because running `bundle install` in the example directory should have also installed all gems required for the Ruby directory. I wonder if `rbenv` is somehow to blame for this as I went through all the steps with `rvm` without issue.

**Comment by frewsxcv** [comment] 2017-04-27 15:36
After running `bundle install` in the `ruby` dir, things seem to be working now. Should I open an issue for handling rbenv?

**Comment by wagenet** [comment] 2017-04-27 16:13
@frewsxcv sure, go ahead and do that. I can't say for sure if it's actually an issue with our setup or with rbenv itself, but it seems worth investigating further.

**Comment by hmcfletch** [comment] 2017-04-28 15:59
I had a similar problem to the initial issue: `Could not find gem 'rake-compiler (~> 0.9.7)' in any...`

After I added `gem 'rake-compiler',  '~> 0.9.7'` to the `Gemfile`, ran `bundle install` and everything seemed to work. It then worked for the other examples as well. If I uninstall `rake-compiler` and `bundle install` again then the other examples.

It looks like there is a missing `rake-compiler` dependency somewhere. Am I missing something?

**Comment by wagenet** [comment] 2017-04-28 16:14
Ah, I figured out what's happening I think. We have `rake-compiler` as a development dependency in the main helix_runtime gem: https://github.com/tildeio/helix/blob/master/ruby/helix_runtime.gemspec#L32. The Gemfiles for the examples point to the local helix_runtime gem, and should install dependencies but probably don't end up installing the development dependencies. The solution is probably to either run `bundle install` in the `ruby` directory first, or add `rake-compiler` to the example Gemfiles.

**Comment by hmcfletch** [comment] 2017-04-28 16:55
I'd suggest adding them to the example `Gemfile`'s. That way the examples stand on their own.

**Comment by wagenet** [comment] 2017-04-28 17:19
@hmcfletch the issue is that the examples don't actually need rake-compiler, they just need the helix_runtime gem to have already been compiled. I think the answer is probably to run `bundle install` here: https://github.com/tildeio/helix/blob/master/examples/calculator/Rakefile#L15.

**Comment by hmcfletch** [comment] 2017-04-28 17:41
ahhhh... makes sense. Also, thanks for the work on this!

**Closed** 2017-04-28 23:46 UTC
Labels: Bug, PR Pending
